### ISSUE TITLE
Unhandled Exception: System.ArgumentException

### ISSUE THREAD

**Issue by Chantal2019** [FalconForceTeam/SOAPHound#1] opened 2024-01-27 15:57 UTC
Thank you for this tool :)

When I want to generate cache  using this command SOAPHound.exe --buildcache -c c:\temp\cache.txt after 20 min or so I get this error :

Facts: I tested the command both as it is and also with domain , dc and username and password and still get this error" 

`Unhandled Exception: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at SOAPHound.Processors.Cache.AddType(String key, Label value)
   at SOAPHound.Program.GenerateCache()
   at SOAPHound.Program.Run(String Server, Int32 Port, NetworkCredential Credential)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at SOAPHound.Program.ParseCommandLineArgs(String[] args)
   at SOAPHound.Program.Main(String[] args)`

**Comment by 0xFF-NK** [comment] 2024-01-29 11:39
Thanks for your feedback, that looks like a duplicate key issue.

We added duplication checks when adding new keys to the cache and committed the changes to main. Can you retry and let us know if the issue is fixed?

**Closed as completed** 2024-01-31 08:50 UTC
